create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  pc_id text not null unique,
  zone text not null,
  plan text not null,
  plan_label text not null,
  booking_date date not null,
  booking_time time not null,
  duration integer not null,
  total integer not null,
  pin_length integer not null,
  start_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

create policy "Public can read bookings"
on public.bookings
for select
to anon
using (true);

create policy "Public can insert bookings"
on public.bookings
for insert
to anon
with check (true);

create policy "Public can delete only expired bookings"
on public.bookings
for delete
to anon
using (expires_at <= now());
